version: "2"
services:
  filebeat:
    image: daisaru11/beats-aws-ecs
    volumes:
      - "./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro"
      - "nginx-log:/var/log/nginx"
    command: filebeat -e -d "*" --plugin beats-aws-ecs.so

  nginx:
    container_name: test-nginx
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "8080:80"
    volumes:
      - "nginx-log:/var/log/nginx"

volumes:
  nginx-log:
