version: "2"
services:
  filebeat:
    image: daisaru11/beats-aws-ecs
    volumes:
      - "./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro"
      - "nginx-log:/var/log/nginx"
    command: filebeat -e -d "*" --plugin beats-aws-ecs.so -modules=nginx -E "output.console.pretty=true"

  nginx:
    container_name: test-nginx
    image: nginx:alpine
    ports:
      - "8080:80"
    command: /bin/sh -c "rm /var/log/nginx/*.log && exec nginx -g 'daemon off;'"
    volumes:
      - "nginx-log:/var/log/nginx"

volumes:
  nginx-log:
